name: "Telegram Uploader"
description: "Upload files to Telegram"
author: 'nikhilbadyal'
inputs:
  API_ID:
    required: true
    description: 'API ID from Telegram.'
  API_HASH:
    required: true
    description: 'API Hash from Telegram.'
  BOT_TOKEN:
    required: true
    description: 'Bot Token (Sender).'
  CHAT_ID:
    required: true
    description: 'Chat to Send(Receiver).'
  STICKER_ID:
    required: false
    description: 'Sticker to Send'
  CHANGELOG_GITHUB_REPOSITORY:
    required: false
    description: 'Repo to Fetch Changelog'
  DOWNLOAD_GITHUB_REPOSITORY:
    required: false
    description: 'Repo to Download assets'
  ASSETS_PATTERN:
    required: false
    description: 'Regex for Asset name match'
branding:
  icon: 'upload-cloud'
  color: 'blue'

runs:
  using: "docker"
  image: "Dockerfile"
