blank_issues_enabled: true
contact_links:
  - name: Community Support
    url: https://github.com/nikhilbadyal/ghaction-telegram-uploader/discussions/new/choose
    about: Please ask and answer questions here.
