"""Strings."""
download_string = "Trying to download {} from {}"
download_done = "Downloaded {}"
fetching_assets = "Fetching latest assets."
no_release_found = "No Release found in {}."
downloaded_all = "Downloading all assets {}."
uploading = "Uploading {}"
initializing_connection = "Initializing connection."
skipping_asset = "Skipping {}."
not_found = "Not Found"
request_failure = "Unable to downloaded assets. {}"
project_name = "ghaction-telegram-uploader"
