name: Push to DockerHub
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - '**.py'
      - 'README.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dockerhub-push:
    uses: nikhilbadyal/ghactions/.github/workflows/dockerhub-push.yml@main
    if: github.repository == 'ghaction-telegram-uploader'
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
