name: GitHub Cleanup

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true
  workflow_dispatch:

jobs:
  cleanup:
    name: GitHub Cleanup
    uses: nikhilbadyal/ghactions/.github/workflows/github-cleanup.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
