name: Pre-commit update Checker

on:
  schedule:
    - cron: "15 2 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  auto-update:
    uses: nikhilbadyal/ghactions/.github/workflows/python-precommit-updater.yml@main
    if: github.repository == 'nikhilbadyal/ghaction-telegram-uploader'
    secrets:
      GH_TOKEN: ${{ secrets.PA_GITHUB_TOKEN }}
    with:
      PYTHON_VERSION: '3.10'
